name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - github-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore
      - name: Build With Maven
        run: mvn clean install
      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save